# Generated by Django 4.2.1 on 2023-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_add_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "user_color",
                    models.CharField(
                        choices=[
                            ("#D32A0E", "Red"),
                            ("#2CD30E", "Green"),
                            ("#64BAF5", "Blue"),
                            ("#F050CE", "Pink"),
                            ("#AC50F0", "Purple"),
                            ("#50F0EE", "Turquoise"),
                            ("#F0EE50", "Yellow"),
                            ("#139713", "Forest Green"),
                            ("#132B97", "Dark Blue"),
                            ("#BF166A", "Dark Pink"),
                            ("#787677", "Gray"),
                            ("#000000", "Black"),
                            ("#DC35ED", "Purple Pink"),
                            ("#C0ED35", "Lime Green"),
                            ("#FB9111", "Orange"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
