# Generated by Django 4.2.1 on 2023-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_contributor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("needs_conversion", models.BooleanField(default=True)),
                ("to_miles_conversion", models.FloatField(null=True)),
                ("calories_per_min", models.IntegerField(null=True)),
            ],
        ),
    ]
