# Generated by Django 4.2.1 on 2023-05-24 19:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_contributor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("needs_conversion", models.BooleanField(default=True)),
                ("to_miles_conversion", models.FloatField(blank=True, null=True)),
                ("calories_per_min", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("distance", models.FloatField()),
                (
                    "ending_coords",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("last_checkpoint", models.IntegerField()),
                (
                    "contributor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.contributor",
                    ),
                ),
                (
                    "exercise_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.exercisetype",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pathgeometry",
                    ),
                ),
            ],
        ),
    ]
